// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "x3.na.tri@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth/dashboard/login": {
            "post": {
                "security": [
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Authenticate dashboard user with email and password",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Dashboard user login",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DashboardLoginDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.DashboardLogin200"
                        }
                    },
                    "400": {
                        "description": "Bad Request or Validation Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.DashboardLogin400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response401"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/dashboard/refresh-token": {
            "post": {
                "security": [
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Refresh authentication token for dashboard user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Dashboard refresh token",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "refreshToken",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshTokenDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token refreshed successfully",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.DashboardRefreshToken200"
                        }
                    },
                    "400": {
                        "description": "Bad Request or Validation Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.DashboardRefreshToken400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized or Invalid Token",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response401"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/category": {
            "get": {
                "security": [
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Retrieve all categories",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Get all categories",
                "responses": {
                    "200": {
                        "description": "List of categories",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.CategoryList200"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/category/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Create a new category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Create a new category",
                "parameters": [
                    {
                        "description": "Category to create",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.CreateDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Category created successfully",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.CategoryCreate201"
                        }
                    },
                    "400": {
                        "description": "Bad Request or Validation Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.CategoryCreate400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response401"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/category/{id}": {
            "get": {
                "security": [
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Retrieve category by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Get category by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Category found",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.CategoryGetById200"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response400"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "404": {
                        "description": "Category not found",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response404"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/category/{id}/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Delete category by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Delete category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Category deleted",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.CategoryDelete200"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response401"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "404": {
                        "description": "Category not found",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response404"
                        }
                    },
                    "409": {
                        "description": "Category has linked entities",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response409"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/category/{id}/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Update category by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Category"
                ],
                "summary": "Update category",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Category update payload",
                        "name": "category",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.UpdateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Category updated",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.CategoryUpdate200"
                        }
                    },
                    "400": {
                        "description": "Bad request or validation error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.CategoryUpdate400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response401"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/dashboard-user/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Create a new dashboard user with the provided details.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Dashboard User"
                ],
                "summary": "Create a new dashboard user",
                "parameters": [
                    {
                        "description": "Dashboard User Create DTO",
                        "name": "dashboardUser",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_dashboard_user_dto.CreateDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Dashboard User Created",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.DashboardUserCreate201"
                        }
                    },
                    "400": {
                        "description": "Bad Request or Validation Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.DashboardUserCreate400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response401"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/image/upload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Upload one or more images with a specific imageType. Requires JWT authentication.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Image"
                ],
                "summary": "Upload images",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type of image (e.g. category)",
                        "name": "imageType",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Image files to upload (multiple allowed)",
                        "name": "images",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Uploaded images info",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/docsResponse.ImageUpload200"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request or Validation Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.ImageUpload400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response401"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "413": {
                        "description": "File too large",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response413"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/line": {
            "get": {
                "security": [
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Retrieve all lines",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Line"
                ],
                "summary": "Get all lines",
                "responses": {
                    "200": {
                        "description": "List of lines",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.LineList200"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/line/create": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Create a new line",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Line"
                ],
                "summary": "Create a new line",
                "parameters": [
                    {
                        "description": "Line to create",
                        "name": "line",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_line_dto.CreateDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Line created successfully",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.LineCreate201"
                        }
                    },
                    "400": {
                        "description": "Bad Request or Validation Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.LineCreate400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response401"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/line/{id}": {
            "get": {
                "security": [
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Retrieve line by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Line"
                ],
                "summary": "Get line by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Line ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Line found",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.LineGetById200"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response400"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "404": {
                        "description": "Line not found",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response404"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/line/{id}/delete": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Delete line by ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Line"
                ],
                "summary": "Delete line",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Line ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Line deleted",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.LineDelete200"
                        }
                    },
                    "400": {
                        "description": "Invalid ID",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response401"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "404": {
                        "description": "Line not found",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response404"
                        }
                    },
                    "409": {
                        "description": "Line has linked entities",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response409"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        },
        "/api/v1/line/{id}/update": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    },
                    {
                        "AppAuth": []
                    }
                ],
                "description": "Update line by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Line"
                ],
                "summary": "Update line",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Line ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Line update payload",
                        "name": "line",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_line_dto.UpdateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Line updated",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.LineUpdate200"
                        }
                    },
                    "400": {
                        "description": "Bad request or validation error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.LineUpdate400"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response401"
                        }
                    },
                    "403": {
                        "description": "Forbidden - Invalid X-AUTH-APP",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response403"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "$ref": "#/definitions/docsResponse.Response500"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "docsResponse.CategoryCreate201": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.CategoryCreate400": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "BAD_REQUEST"
                    ]
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/docsResponse.categoryErrorField"
                    }
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Bad request or validation error"
                }
            }
        },
        "docsResponse.CategoryDelete200": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.CategoryGetById200": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.CategoryList200": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO"
                    }
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.CategoryUpdate200": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.CategoryUpdate400": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "BAD_REQUEST"
                    ]
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/docsResponse.categoryErrorField"
                    }
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Bad request or validation error"
                }
            }
        },
        "docsResponse.DashboardLogin200": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_auth_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.DashboardLogin400": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "BAD_REQUEST"
                    ]
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/docsResponse.authErrorField"
                    }
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Bad request or validation error"
                }
            }
        },
        "docsResponse.DashboardRefreshToken200": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_auth_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.DashboardRefreshToken400": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "BAD_REQUEST"
                    ]
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/docsResponse.authErrorField"
                    }
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Bad request or validation error"
                }
            }
        },
        "docsResponse.DashboardUserCreate201": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.DashboardUserCreate400": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "BAD_REQUEST"
                    ]
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/docsResponse.dashboardUserErrorField"
                    }
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Bad request or validation error"
                }
            }
        },
        "docsResponse.ImageUpload200": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_image_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.ImageUpload400": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "BAD_REQUEST"
                    ]
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/docsResponse.imageErrorField"
                    }
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Bad request or validation error"
                }
            }
        },
        "docsResponse.LineCreate201": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_line_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.LineCreate400": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "BAD_REQUEST"
                    ]
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/docsResponse.categoryErrorField"
                    }
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Bad request or validation error"
                }
            }
        },
        "docsResponse.LineDelete200": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_line_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.LineGetById200": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_line_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.LineList200": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_line_dto.ResponseDTO"
                    }
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.LineUpdate200": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/haircompany-shop-rest_internal_modules_v1_line_dto.ResponseDTO"
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "docsResponse.LineUpdate400": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "BAD_REQUEST"
                    ]
                },
                "fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/docsResponse.categoryErrorField"
                    }
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Bad request or validation error"
                }
            }
        },
        "docsResponse.Response400": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "BAD_REQUEST"
                    ]
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Bad request or validation error"
                }
            }
        },
        "docsResponse.Response401": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "UNAUTHORIZED"
                    ]
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Unauthorized"
                }
            }
        },
        "docsResponse.Response403": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "FORBIDDEN"
                    ]
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Forbidden"
                }
            }
        },
        "docsResponse.Response404": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "NOT_FOUND"
                    ]
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Resource not found"
                }
            }
        },
        "docsResponse.Response409": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "HAS_LINKED_ENTITIES"
                    ]
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Conflict"
                }
            }
        },
        "docsResponse.Response413": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "REQUEST_TOO_LARGE"
                    ]
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Request entity too large"
                }
            }
        },
        "docsResponse.Response500": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "SERVER_ERROR"
                    ]
                },
                "isSuccess": {
                    "type": "boolean",
                    "example": false
                },
                "message": {
                    "type": "string",
                    "example": "Internal server error"
                }
            }
        },
        "docsResponse.authErrorField": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "REQUIRED",
                        "INVALID_EMAIL",
                        "MIN_LENGTH",
                        "MAX_LENGTH",
                        "INVALID_TOKEN"
                    ]
                },
                "field": {
                    "type": "string",
                    "enum": [
                        "email",
                        "password",
                        "refreshToken"
                    ]
                }
            }
        },
        "docsResponse.categoryErrorField": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "NOT_UNIQUE",
                        "NOT_FOUND"
                    ]
                },
                "field": {
                    "type": "string",
                    "enum": [
                        "name",
                        "slug",
                        "parentId"
                    ]
                }
            }
        },
        "docsResponse.dashboardUserErrorField": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "enum": [
                        "NOT_UNIQUE",
                        "NOT_FOUND"
                    ]
                },
                "field": {
                    "type": "string",
                    "enum": [
                        "name",
                        "slug",
                        "parentId"
                    ]
                }
            }
        },
        "docsResponse.imageErrorField": {
            "type": "object",
            "properties": {
                "errorCode": {
                    "type": "string",
                    "example": "INVALID_FORMAT"
                },
                "field": {
                    "type": "string",
                    "example": "images"
                }
            }
        },
        "dto.DashboardLoginDTO": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 8
                }
            }
        },
        "dto.RefreshTokenDTO": {
            "type": "object",
            "required": [
                "refreshToken"
            ],
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "haircompany-shop-rest_internal_modules_v1_auth_dto.ResponseDTO": {
            "type": "object",
            "properties": {
                "refreshExpiresAt": {
                    "type": "integer"
                },
                "refreshToken": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "haircompany-shop-rest_internal_modules_v1_category_dto.CreateDTO": {
            "type": "object",
            "required": [
                "headerImage",
                "image",
                "name",
                "slug",
                "sortIndex"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "headerImage": {
                    "type": "string",
                    "maxLength": 255
                },
                "image": {
                    "type": "string",
                    "maxLength": 255
                },
                "isActive": {
                    "type": "boolean"
                },
                "isShade": {
                    "type": "boolean"
                },
                "isVisibleInMenu": {
                    "type": "boolean"
                },
                "isVisibleOnMain": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                },
                "parentId": {
                    "description": "Nullable, can be zero",
                    "type": "integer",
                    "minimum": 0
                },
                "seoDescription": {
                    "type": "string"
                },
                "seoKeys": {
                    "type": "string"
                },
                "seoTitle": {
                    "type": "string",
                    "maxLength": 255
                },
                "slug": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                },
                "sortIndex": {
                    "type": "integer",
                    "maximum": 9999,
                    "minimum": 0
                }
            }
        },
        "haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "headerImage": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "image": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isShade": {
                    "type": "boolean"
                },
                "isVisibleInMenu": {
                    "type": "boolean"
                },
                "isVisibleOnMain": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "type": "integer"
                },
                "seoDescription": {
                    "type": "string"
                },
                "seoKeys": {
                    "type": "string"
                },
                "seoTitle": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "sortIndex": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "haircompany-shop-rest_internal_modules_v1_category_dto.UpdateDTO": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "headerImage": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "isShade": {
                    "type": "boolean"
                },
                "isVisibleInMenu": {
                    "type": "boolean"
                },
                "isVisibleOnMain": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                },
                "parentId": {
                    "type": "integer"
                },
                "seoDescription": {
                    "type": "string"
                },
                "seoKeys": {
                    "type": "string"
                },
                "seoTitle": {
                    "type": "string"
                },
                "slug": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                },
                "sortIndex": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "haircompany-shop-rest_internal_modules_v1_dashboard_user_dto.CreateDTO": {
            "type": "object",
            "required": [
                "email",
                "password",
                "role"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 8
                },
                "role": {
                    "type": "string",
                    "enum": [
                        "admin",
                        "manager"
                    ]
                }
            }
        },
        "haircompany-shop-rest_internal_modules_v1_image_dto.ResponseDTO": {
            "type": "object",
            "properties": {
                "image": {
                    "type": "string"
                }
            }
        },
        "haircompany-shop-rest_internal_modules_v1_line_dto.CreateDTO": {
            "type": "object",
            "required": [
                "color",
                "name"
            ],
            "properties": {
                "color": {
                    "type": "string",
                    "example": "#FF5733"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                }
            }
        },
        "haircompany-shop-rest_internal_modules_v1_line_dto.ResponseDTO": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string",
                    "example": "#FF5733"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2023-10-01T12:00:00Z"
                },
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Line Name"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-10-01T12:00:00Z"
                }
            }
        },
        "haircompany-shop-rest_internal_modules_v1_line_dto.UpdateDTO": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 255,
                    "minLength": 3
                }
            }
        }
    },
    "securityDefinitions": {
        "AppAuth": {
            "description": "Ключ аутентификации приложения из AUTH_APP_KEY",
            "type": "apiKey",
            "name": "X-AUTH-APP",
            "in": "header"
        },
        "BearerAuth": {
            "description": "Введите токен в формате: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"http", "https"},
	Title:            "Hair Company Shop API",
	Description:      "REST API для магазина бренда Hair Company",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
