definitions:
  docsResponse.Category201:
    properties:
      data:
        $ref: '#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO'
      isSuccess:
        example: true
        type: boolean
    type: object
  docsResponse.Category500:
    properties:
      errorCode:
        enum:
        - SERVER_ERROR
        type: string
      isSuccess:
        example: false
        type: boolean
      message:
        type: string
    type: object
  docsResponse.CategoryCreate400:
    properties:
      errorCode:
        enum:
        - BAD_REQUEST
        type: string
      fields:
        items:
          $ref: '#/definitions/docsResponse.createField'
        type: array
      isSuccess:
        example: false
        type: boolean
      message:
        type: string
    type: object
  docsResponse.CategoryDelete200:
    properties:
      data:
        $ref: '#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO'
      isSuccess:
        example: true
        type: boolean
    type: object
  docsResponse.CategoryDelete400:
    properties:
      errorCode:
        enum:
        - BAD_REQUEST
        type: string
      isSuccess:
        example: false
        type: boolean
      message:
        type: string
    type: object
  docsResponse.CategoryDelete404:
    properties:
      errorCode:
        enum:
        - NOT_FOUND
        type: string
      isSuccess:
        example: false
        type: boolean
      message:
        type: string
    type: object
  docsResponse.CategoryDelete409:
    properties:
      errorCode:
        enum:
        - HAS_LINKED_ENTITIES
        type: string
      isSuccess:
        example: false
        type: boolean
      message:
        type: string
    type: object
  docsResponse.CategoryGetById200:
    properties:
      data:
        $ref: '#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO'
      isSuccess:
        example: true
        type: boolean
    type: object
  docsResponse.CategoryGetById400:
    properties:
      errorCode:
        enum:
        - BAD_REQUEST
        type: string
      isSuccess:
        example: false
        type: boolean
      message:
        type: string
    type: object
  docsResponse.CategoryGetById404:
    properties:
      errorCode:
        enum:
        - NOT_FOUND
        type: string
      isSuccess:
        example: false
        type: boolean
      message:
        type: string
    type: object
  docsResponse.CategoryList200:
    properties:
      data:
        items:
          $ref: '#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO'
        type: array
      isSuccess:
        example: true
        type: boolean
    type: object
  docsResponse.CategoryUpdate200:
    properties:
      data:
        $ref: '#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO'
      isSuccess:
        example: true
        type: boolean
    type: object
  docsResponse.CategoryUpdate400:
    properties:
      errorCode:
        enum:
        - BAD_REQUEST
        type: string
      fields:
        items:
          $ref: '#/definitions/docsResponse.createField'
        type: array
      isSuccess:
        example: false
        type: boolean
      message:
        type: string
    type: object
  docsResponse.ImageUpload200:
    properties:
      data:
        $ref: '#/definitions/haircompany-shop-rest_internal_modules_v1_image_dto.ResponseDTO'
      isSuccess:
        example: true
        type: boolean
    type: object
  docsResponse.ImageUpload400:
    properties:
      errorCode:
        enum:
        - BAD_REQUEST
        type: string
      fields:
        items:
          $ref: '#/definitions/docsResponse.imageField'
        type: array
      isSuccess:
        example: false
        type: boolean
      message:
        example: validation errors occurred
        type: string
    type: object
  docsResponse.ImageUpload413:
    properties:
      errorCode:
        enum:
        - REQUEST_TOO_LARGE
        type: string
      isSuccess:
        example: false
        type: boolean
      message:
        example: file too large
        type: string
    type: object
  docsResponse.ImageUpload500:
    properties:
      errorCode:
        enum:
        - SERVER_ERROR
        type: string
      isSuccess:
        example: false
        type: boolean
      message:
        example: failed to upload image
        type: string
    type: object
  docsResponse.createField:
    properties:
      errorCode:
        enum:
        - NOT_UNIQUE
        - NOT_FOUND
        type: string
      field:
        enum:
        - name
        - slug
        - parentId
        type: string
    type: object
  docsResponse.imageField:
    properties:
      errorCode:
        example: INVALID_FORMAT
        type: string
      field:
        example: images
        type: string
    type: object
  haircompany-shop-rest_internal_modules_v1_category_dto.CreateDTO:
    properties:
      description:
        type: string
      headerImage:
        maxLength: 255
        type: string
      image:
        maxLength: 255
        type: string
      isActive:
        type: boolean
      isShade:
        type: boolean
      isVisibleInMenu:
        type: boolean
      isVisibleOnMain:
        type: boolean
      name:
        maxLength: 255
        minLength: 3
        type: string
      parentId:
        description: Nullable, can be zero
        minimum: 0
        type: integer
      seoDescription:
        type: string
      seoKeys:
        type: string
      seoTitle:
        maxLength: 255
        type: string
      slug:
        maxLength: 255
        minLength: 3
        type: string
      sortIndex:
        maximum: 9999
        minimum: 0
        type: integer
    required:
    - headerImage
    - image
    - name
    - slug
    - sortIndex
    type: object
  haircompany-shop-rest_internal_modules_v1_category_dto.ResponseDTO:
    properties:
      createdAt:
        type: string
      description:
        type: string
      headerImage:
        type: string
      id:
        type: integer
      image:
        type: string
      isActive:
        type: boolean
      isShade:
        type: boolean
      isVisibleInMenu:
        type: boolean
      isVisibleOnMain:
        type: boolean
      name:
        type: string
      parentId:
        type: integer
      seoDescription:
        type: string
      seoKeys:
        type: string
      seoTitle:
        type: string
      slug:
        type: string
      sortIndex:
        type: integer
      updatedAt:
        type: string
    type: object
  haircompany-shop-rest_internal_modules_v1_category_dto.UpdateDTO:
    properties:
      description:
        type: string
      headerImage:
        type: string
      image:
        type: string
      isActive:
        type: boolean
      isShade:
        type: boolean
      isVisibleInMenu:
        type: boolean
      isVisibleOnMain:
        type: boolean
      name:
        maxLength: 255
        minLength: 3
        type: string
      parentId:
        type: integer
      seoDescription:
        type: string
      seoKeys:
        type: string
      seoTitle:
        type: string
      slug:
        maxLength: 255
        minLength: 3
        type: string
      sortIndex:
        minimum: 0
        type: integer
    type: object
  haircompany-shop-rest_internal_modules_v1_image_dto.ResponseDTO:
    properties:
      image:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/category:
    get:
      description: Retrieve all categories
      produces:
      - application/json
      responses:
        "200":
          description: List of categories
          schema:
            $ref: '#/definitions/docsResponse.CategoryList200'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/docsResponse.Category500'
      summary: Get all categories
      tags:
      - Category
    post:
      consumes:
      - application/json
      description: Create a new category
      parameters:
      - description: Category to create
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.CreateDTO'
      produces:
      - application/json
      responses:
        "201":
          description: Category created successfully
          schema:
            $ref: '#/definitions/docsResponse.Category201'
        "400":
          description: Bad Request or Validation Error
          schema:
            $ref: '#/definitions/docsResponse.CategoryCreate400'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/docsResponse.Category500'
      summary: Create a new category
      tags:
      - Category
  /api/v1/category/{id}:
    delete:
      description: Delete category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Category deleted
          schema:
            $ref: '#/definitions/docsResponse.CategoryDelete200'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/docsResponse.CategoryDelete400'
        "404":
          description: Category not found
          schema:
            $ref: '#/definitions/docsResponse.CategoryDelete404'
        "409":
          description: Category has linked entities
          schema:
            $ref: '#/definitions/docsResponse.CategoryDelete409'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/docsResponse.Category500'
      summary: Delete category
      tags:
      - Category
    get:
      description: Retrieve category by its ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Category found
          schema:
            $ref: '#/definitions/docsResponse.CategoryGetById200'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/docsResponse.CategoryGetById400'
        "404":
          description: Category not found
          schema:
            $ref: '#/definitions/docsResponse.CategoryGetById404'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/docsResponse.Category500'
      summary: Get category by ID
      tags:
      - Category
    put:
      consumes:
      - application/json
      description: Update category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category update payload
        in: body
        name: category
        required: true
        schema:
          $ref: '#/definitions/haircompany-shop-rest_internal_modules_v1_category_dto.UpdateDTO'
      produces:
      - application/json
      responses:
        "200":
          description: Category updated
          schema:
            $ref: '#/definitions/docsResponse.CategoryUpdate200'
        "400":
          description: Bad request or validation error
          schema:
            $ref: '#/definitions/docsResponse.CategoryUpdate400'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/docsResponse.Category500'
      summary: Update category
      tags:
      - Category
  /api/v1/image/upload:
    post:
      consumes:
      - multipart/form-data
      description: Upload one or more images with a specific imageType
      parameters:
      - description: Type of image (e.g. category)
        in: formData
        name: imageType
        required: true
        type: string
      - description: Image files to upload (multiple allowed)
        in: formData
        name: images
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Uploaded images info
          schema:
            items:
              $ref: '#/definitions/docsResponse.ImageUpload200'
            type: array
        "400":
          description: Bad Request or Validation Error
          schema:
            $ref: '#/definitions/docsResponse.ImageUpload400'
        "413":
          description: File too large
          schema:
            $ref: '#/definitions/docsResponse.ImageUpload413'
        "500":
          description: Server Error
          schema:
            $ref: '#/definitions/docsResponse.ImageUpload500'
      summary: Upload images
      tags:
      - Image
swagger: "2.0"
